### ISSUE TITLE
Cannot run without checking ARKit Uses Facetracking.

### ISSUE THREAD

**Issue by TakuKobayashi** [algomystic/TheParallaxView#17]
Hello.
I tried to run with reference to the README(Detailed Build Instructions), but it was not run.
So, I investigated the cause and found out that It wasn't checking a mark "ARKit Uses Facetracking" in ARKitSettings.asset. (UnityARKitPlugin/Resources/UnityARKitPlugin/ARKitSettings.asset)
Would you add a check mark to "ARKit Uses Facetracking" in the README?

**Comment by algomystic** [comment]
Thanks!
Hmm, I've added ARKitSettings.asset to the repo (in Assets/) so I thought it would use that one rather than the one in UnityARKitPlugin/Resources/UnityARKitPlugin/ARKitSettings.asset. Maybe not? How could I include those settings and make sure they're used? If I can't figure it out and nobody here can help me, I will add that step to the build instructions.

**Comment by algomystic** [comment]
I've looked into it and you are correct. The settings file needs to be in the UnityARKitPlugin/Resources/UnityARKitPlugin/ folder. I'll update the readme.

**Comment by algomystic** [comment]
This has been added to README now, closing the issue

**Comment by TakuKobayashi** [comment]
Thanks to be added!
